# https://github.com/marketplace/actions/cypress-io
# https://github.com/marketplace/actions/deploy-to-github-pages
name: Deploy React App
on: push
jobs:
  install_and_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
      - name: Lint application
        run: npm run lint

  # test:
  #   runs-on: ubuntu-latest
  #   needs: lint
  #   steps:
  #     - name: test
  #       run: echo test
  # strategy:
  #   fail-fast: false
  #   matrix:
  #     # run copies of the current job in parallel
  #     containers: [1, 2, 3, 4, 5]

  deploy:
    runs-on: ubuntu-latest
    needs: install_and_lint
    steps:
      # - name: E2E test on Chrome
      #   uses: cypress-io/github-action@v5
      #   with:
      #     # we have already installed all dependencies above
      #     install: false
      #     browser: chrome
      #     start: npm run dev
      #     wait-on-timeout: 120
      #     spec: cypress/e2e/spec.cy.ts
      #     parallel: true
      #     group: 'UI - Chrome'
      #     wait-on: 'http://localhost:5173'
      #     parallel: true

      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages
