# https://github.com/marketplace/actions/cypress-io
# https://github.com/marketplace/actions/deploy-to-github-pages
name: Deploy React App
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
      - name: Lint application
        run: npm run lint
      - name: E2E test on Chrome
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          spec: cypress/e2e/spec.cy.ts
      - name: Build application
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages
